import { useEffect, useState } from "react";
import { API_BASE_URL } from "../config/api";
type Item = { id:number; service_date:string; adult_attendance:number; sunday_school_attendance:number; main_service_offering:number; sunday_school_offering:number; created_by:string };
type Props = { selectedBranch:string; backPage:string; setPage:(page:string)=>void };
export default function ServiceStatisticsReport({ selectedBranch, backPage, setPage }: Props) {
 const today = new Date().toISOString().slice(0,10); const [date, setDate] = useState(""); const [month, setMonth] = useState(String(new Date().getMonth() + 1)); const [year, setYear] = useState(String(new Date().getFullYear())); const [items,setItems]=useState<Item[]>([]); const [summary,setSummary]=useState<any>({}); const [refreshKey, setRefreshKey] = useState(0); const [sending, setSending] = useState(false);
 useEffect(() => { const query = new URLSearchParams({ branch:selectedBranch }); if(date) query.set("service_date",date); else { if(month) { query.set("month",month); query.set("year",year || String(new Date().getFullYear())); } else if(year) query.set("year",year); } fetch(`${API_BASE_URL}/service-statistics?${query}`).then(r=>r.json()).then(d=>{setItems(d.items||[]);setSummary(d.summary||{});}).catch(()=>{setItems([]);setSummary({});}); },[selectedBranch,date,month,year,refreshKey]);
 const sendMonthlyReport = async () => { if (!month || !year) return alert("Choose a month and year before sending the report."); setSending(true); try { const response = await fetch(`${API_BASE_URL}/bishop-oversight-reports/generate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ branch: selectedBranch, generated_by: `Service Statistics ${month}/${year}` }) }); const data = await response.json(); if (!response.ok) return alert(data.detail || "Unable to send the report."); alert("Monthly report sent to Church Oversight."); setPage("church-oversight"); } finally { setSending(false); } };
 const cards = [["Adult Attendance",summary.adult_attendance||0],["Sunday School Attendance",summary.sunday_school_attendance||0],["Main Service Offering",money(summary.main_service_offering)],["Sunday School Offering",money(summary.sunday_school_offering)]];
 return <main style={page}><button onClick={()=>setPage(backPage)} style={back}>← Back</button><h1>Service Statistics</h1><p style={{color:"#475569"}}>{selectedBranch} Branch · attendance and offering analysis</p><section style={filters}><label>Date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setMonth("");setYear("");}} /></label><label>Month<input type="number" min="1" max="12" placeholder="1–12" value={month} onChange={e=>{setMonth(e.target.value);setDate("");}} /></label><label>Year<input type="number" placeholder="2026" value={year} onChange={e=>{setYear(e.target.value);setDate("");}} /></label><button onClick={()=>{setDate(today);setMonth("");setYear("");}} style={back}>Today</button><button onClick={()=>setRefreshKey(value=>value+1)} style={back}>Refresh</button><button onClick={sendMonthlyReport} disabled={sending} style={back}>{sending ? "Sending…" : "Send Monthly Report"}</button></section><h2>{date ? "Today's Summary" : "Monthly Summary"}</h2><section style={cardGrid}>{cards.map(([label,value])=><article key={String(label)} style={card}><p>{label}</p><strong>{value}</strong></article>)}</section><section style={tableWrap}><h2>Recorded Services</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Date","Adult","Sunday School","Main Offering","Sunday School Offering","Recorded by"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{items.length ? items.map(item=><tr key={item.id}><td style={td}>{item.service_date}</td><td style={td}>{item.adult_attendance}</td><td style={td}>{item.sunday_school_attendance}</td><td style={td}>{money(item.main_service_offering)}</td><td style={td}>{money(item.sunday_school_offering)}</td><td style={td}>{item.created_by}</td></tr>) : <tr><td style={td} colSpan={6}>No statistics found for this filter.</td></tr>}</tbody></table></section></main>;
}
const money=(v:any)=>`KSh ${Number(v||0).toLocaleString()}`;
const page={minHeight:"100vh",padding:36,background:"#f8fafc",fontFamily:"Arial, sans-serif",color:"#0f172a"} as const;
const back={padding:"10px 16px",border:"none",borderRadius:8,background:"#0f3d82",color:"white",cursor:"pointer"} as const;
const filters={display:"flex",gap:14,flexWrap:"wrap",alignItems:"end",background:"white",padding:18,borderRadius:14} as const;
const cardGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:16} as const;
const card={background:"linear-gradient(135deg,#1d4ed8,#0f3d82)",color:"white",padding:20,borderRadius:14} as const;
const tableWrap={marginTop:26,background:"white",padding:20,borderRadius:14,overflowX:"auto"} as const;
const th={textAlign:"left",padding:12,borderBottom:"2px solid #e2e8f0"} as const;
const td={padding:12,borderBottom:"1px solid #e2e8f0"} as const;
